image: comp1531/basic:latest

cache:
  paths:
    - node_modules

stages:
  - checks
    
before_script:
  - echo "This message is echoed at the very start!"

testing:
  stage: checks
  script:
    - echo 'Add testing here'
    - echo 'echo!'

typecheck:
  stage: checks
  script:
    - npm run tsc

linting:
  stage: checks
  script:
    - npm run lint

